module.exports = {
  theme: {
    extend: {
      colors: {
        brand: '#364c8b',
        accent: {
          // generated by Adobe color wheel (monochromatic scheme) based on brand blue
          200: '#b0c4ff',
          400: '#638bff',
          default: '#4f70cc',
          800: '#58627f',
        },
      },
      lineHeight: {
        tighter: 1.125,
      },
    },
  },
  plugins: [
    require('tailwind-css-variables')(
      {
        // modules
        // colors: 'color',
        screens: false,
        fontFamily: false,
        // fontSize: 'text',
        // fontWeight: 'font',
        // lineHeight: 'leading',
        // letterSpacing: 'tracking',
        backgroundSize: false,
        // borderWidth: 'border',
        // borderRadius: 'rounded',
        width: false,
        height: false,
        minWidth: false,
        minHeight: false,
        maxWidth: 'max-w',
        maxHeight: false,
        padding: false,
        margin: 'space',
        boxShadow: 'shadow',
        zIndex: false,
        opacity: false,
      },
      {
        // options
      },
    ),
  ],
}
